config/routes.rb
Rails.application.routes.draw do
root to: "home#top"
devise_for :users

resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
resources :users, only: [:create, :index, :show, :edit, :update]

get 'home/about' => 'home#about', as: 'about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  
  has_one_attached :profile_image
  
  validates :name, presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :autheniticate_user, {only: [:edit, :update]}
  before_action :is_matching_login_user, only: [:edit, :update]
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    flash[:notice] = "Signed in successfully."
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    flash[:notice] = "Signed out successfully."
    root_path
  end
  
  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book1 = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(book.id)
    else
      @book = book
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    unless book.user_id == current_user.id
      redirect_to books_path
    end
  end
  
  def autheniticate_user
    if current_user == nil
    redirect_to new_user_session_path
    end
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def top
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
 def index
    @users = User.all
    @user = current_user
    @book = Book.new
 end
 
 def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path(@book.id)
  end
 
 def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
   def book_params
    params.require(:book).permit(:title, :body)
    end

  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  
  def autheniticate_user
    if current_user == nil
    redirect_to new_user_session_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<h1>New book</h1>
  <%= form_with model: book do |f| %>
    <p>Title</p>
      <%= f.text_field :title %>
    <p>Opinion</p>
      <%= f.text_area :body %><br>

    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/edit.html.erb
<div class="mx-auto mt-3">
  <h1>Editing Book</h1>
    <div class="my-2">
      <% if @book.errors.any? %>
        <h3><%= @book.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  
  <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
  <div class="mb-3">
    <p>Title</p>
    <%= f.text_field :title %>
  </div>
  <div class="mb-2">
    <p>Opinion</p>
    <%= f.text_area :body %><br>
  </div>
  <div class="mb-3">
    <%= f.submit 'Update Book' %>
  </div>
  <% end %>
  
  <div class="d-inline"><%= link_to "Show", book_path(@book.id) %></div>
  <div class="d-inline">|</div>
  <div class="d-inline"><%= link_to "Back", books_path %></div>
</div>

app/views/books/index.html.erb
<!-- booksのindex -->

<!-- バリデーションによるエラー文 -->
<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-3">
      <!-- ユーザープロフィール -->
      <%= render 'users/info', user:@user %>
      <!-- プロフィール編集 -->
      <%= render 'users/editlink', user: @user %>
      <div class="mt-4 offset-md-1">
        <!-- 新規投稿フォーム -->
        <%= render 'new', book:@book %>
      </div>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table table-hover w-100">
        <thead>
          <tr>
            <th scope="col" style="width: 10%"> </th>
            <th scope="col" style="width: 10%">Title</th>
            <th scope="col" style="width: 20%">Opinion</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <td>
            <!-- アカウント画像 -->
            <%= link_to user_path(book.user_id) do %>
            <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
          </td>
          <td>
            <!-- 本のタイトル -->
            <%= link_to book_path(book.id) do %>
            <%= book.title %>
            <% end %>
          </td>
          <td>
            <!-- 本の紹介文 -->
            <%= book.body %>
          </td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<!-- bookの詳細ページ -->

<%= flash[:notice] %>

<div class="container mt-5">
  <div class="row">
    
    <div class="col-md-3">
      <div class="d-flex flex-column">
      <!-- ユーザープロフィール -->
      <%= render 'users/info', user:@book.user %>
      <!-- プロフィール編集 -->
      <%= render 'users/editlink', user: @user %>
      <div class="mt-3">
        <!-- 新規投稿フォーム -->
        <%= render 'new', book:@book1 %>
      </div>
      </div>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
        <table class="table w-100">
          <tbody>
            <td>
              <!-- アカウント画像 -->
              <%= link_to user_path(@user.id) do %>
                <p><%= image_tag @book.user.get_profile_image(100,100) %></p>
              <% end %>
              <!-- ユーザー名 -->
              <%= link_to user_path(@user.id) do %>
                <P><%= @book.user.name %></P>
              <% end %>
            </td>
            <td>
              <!-- 本のタイトル -->
              <%= link_to book_path(@book.id) do %>
                <p><%= @book.title %></P>
              <% end %>
            </td>
            <td>
              <!-- 本の紹介文 -->
              <p><%= @book.body %></P>
            </td>
              <% if @book.user == current_user %>
            <td>
              <%= link_to edit_book_path(@book.id), class: 'text-light' do %>
                <button type="button" class="btn btn-success w-auto">Edit
                </button>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class: 'text-light' do %>
                <button type="button" class="btn btn-danger w-auto">Destroy
                </button>
              <% end %>
            </td>
              <% end %>
         </tbody>
        </table>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<div class="mx-auto mt-3">
  <h1>Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
</div>

app/views/home/top.html.erb
<%= flash[:notice] %>
<div class="mx-auto mt-3">
  <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
  <p>In <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
  <p>you can share and exchange your opinions , inpressions , and emotions</p>
  <p>about various books!</p>
      
  <div class="text-center">
    <div class="my-3">
      <%= link_to new_user_session_path, class: 'text-light' do %>
        <button type="button" class="btn btn-info w-75">Log in
        </button>
      <% end %>
    </div>
    <div class="my-3">
      <%= link_to new_user_registration_path, class: 'text-light' do %>
        <button type="button" class="btn btn-success w-75">Sign up
        </button>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          
          <p class="h3">
            <strong><%= link_to "Bookers", root_path, class: 'nav-link text-light' %></strong>
          </p>
          
          <!-- ハンバーガーアイコン部分 -->
          <button class="flex-row navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                    <i class="fas fa-home" style="color: white;"></i>Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to users_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-users" style="color: white;"></i>Users
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to books_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-book-open" style="color: white;"></i>Books
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-out-alt" style="color: white;"></i>Log out
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to root_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-home" style="color: white;"></i>Home
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to about_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-link" style="color: white;"></i>About
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-user-plus" style="color: white;"></i>Sign up
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                    <i class="fas fa-sign-in-alt" style="color: white;"></i>Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
  
  <footer class="text-center mt-5 mb-10">
    <p>CopyRight Infratop.inc</p>
  </footer>
  
</html>

app/views/users/_editlink.html.erb
<%= link_to edit_user_path(user.id), class: 'text-dark' do %>
<button class="btn btn-outline-secondary w-100">
  <i class="fas fa-user-cog"></i>
</button>
<% end %>

app/views/users/_info.html.erb
<!-- ユーザーの詳細 -->
  <div>
  <h1>User info</h1>
    <%= image_tag user.get_profile_image(100,100) %>
    <table class="table">
      <tbody>
        <tr>
          <th>name</th>
          <td><strong><%= user.name %></strong></td>
        </tr>
        <tr>
          <th>introduction</th>
          <td><strong><%= user.introduction %></strong></td>
        </tr>
      </tbody>
    </table>
  </div>

app/views/users/edit.html.erb
<div class="mx-auto mt-3">
  <h1>User info</h1>
    <div class="my-2">
      <% if @user.errors.any? %>
        <h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  
    <%= form_with model: @user do |f| %>
    <div class="mb-3">
      <!-- ユーザーネーム　-->
      <label for="inputName">Name</label><br>
      <%= f.text_field :name, autofocus: true, id:"inputName" %><br>
    </div>
    <div class="mb-3">
      <!-- アカウント画像 -->
      <label for="inputImage">Image</label><br>
      <%= f.file_field :profile_image, accept: "image/*" %><br>
    </div>
    <div class="mb-3">
      <!-- 自己紹介文 -->
      <label for="inputIntroduction">Introduction</label><br>
      <%= f.text_area :introduction, id:"inputIntroduction" %><br>
    </div>
    <%= f.submit "Update User" %>
  <% end %>
</div>

app/views/users/index.html.erb
<!-- ログインユーザーのindexページ -->
<%= flash[:notice] %>
<div class="container mt-5">
  <div class="row">
    <div class="col-md-3">
      <!-- ユーザープロフィール -->
      <%= render 'info', user:@user %>
      <!-- プロフィール編集 -->
      <%= render 'editlink', user: @user %>
      <div class="mt-3">
        <!-- 新規投稿フォーム -->
        <%= render 'books/new', book:@book %>
      </div>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <!-- 投稿しているユーザー一覧 -->
      <h1>Users</h1>
      <table class="table w-100">
        <thead>
          <tr>
            <th scope="col" style="width: 10%">image</th>
            <th scope="col" style="width: 20%">name</th>
            <th scope="col" style="width: 10%"> </th>
          </tr>
        </thead>
        <% @users.each do |user| %>
          <tbody>
            <td>
              <!-- アカウント画像 -->
              <%= image_tag user.get_profile_image(100,100) %>
            </td>
            <td>
              <!-- ユーザーネーム -->
              <%= user.name %>
            </td>
            <td>
              <!-- ユーザー詳細ページへのリンク -->
              <%= link_to user_path(user.id) do %>
              <p>Show</p>
              <% end %>
            </td>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- ログインユーザーの投稿一覧 -->
<%= flash[:notice] %>
<div class="container mt-5">
  <div class="row">
    
    <div class="col-md-3">
      <div class="d-flex flex-column">
        <!-- ユーザープロフィール -->
        <%= render 'info', user:@user %>
      </div>
      <!-- プロフィール編集 -->
      <%= render 'editlink', user: @user %>
      <div class="mt-4">
        <!-- 新規投稿フォーム -->
        <%= render 'books/new', book:@book %>
      </div>
    </div>
    
    <div class="col-md-8 offset-md-1">
      <!-- ログインユーザーの投稿一覧 -->
      <h1>Books</h1>
        <table class="table table-hover w-100">
          <thead>
            <tr>
              <th scope="col" style="width: 10%"> </th>
              <th scope="col" style="width: 10%">Title</th>
              <th scope="col" style="width: 20%">Opinion</th>
            </tr>
          </thead>
          <% @books.each do |book| %>
          <tbody>
            <td>
            <!-- アカウント画像 -->
            <%= link_to user_path(@user.id) do %>
              <%= image_tag book.user.get_profile_image(100,100) %>
            <% end %>
            </td>
            <td>
            <!-- 本のタイトル -->
            <%= link_to book_path(book.id) do %>
              <%= book.title %>
            <% end %>
            </td>
            <td>
            <!-- 本の紹介文 -->
             <%= book.body %>
            </td>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>